name: CI/CD Pipeline bedrock

on:
  push:
    branches:
      - main

jobs:
  dockerize-spring-boot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Unit Tests
        working-directory: ./ayush
        run: ./mvnw test

      - name: Upload JUnit Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: ayush/target/surefire-reports/

      - name: Run SpotBugs
        working-directory: ./ayush  
        run: ./mvnw com.github.spotbugs:spotbugs-maven-plugin:4.7.3.4:spotbugs

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: ayush/target/spotbugsXml.xml
          if-no-files-found: warn

      - name: Run OWASP Dependency Check
        working-directory: ./ayush
        run: |
          ./mvnw org.owasp:dependency-check-maven:8.4.0:check \
            -DskipSystemScope=true \
            -DskipProvidedScope=true \
            -DskipRuntimeScope=true \
            -DskipTestScope=true \
            -DskipDependencyManagement=true \
            -DnvdApiKeyDisabled=true \
            -Dnoupdate=true \
            -DfailBuildOnAnyVuln=false \
            -DretireJsAnalyzerEnabled=false \
            -DnodeAnalyzerEnabled=false \
            -DassemblyAnalyzerEnabled=false \
            -DarchiveAnalyzerEnabled=false \
            -DjarAnalyzerEnabled=false \
            -DpyPackageAnalyzerEnabled=false \
            -DrubygemsAnalyzerEnabled=false \
            -DopenSSLAnalyzerEnabled=false \
            -DcmakeAnalyzerEnabled=false \
            -DautoconfAnalyzerEnabled=false \
            -DcomposerAnalyzerEnabled=false \
            -DnuspecAnalyzerEnabled=false \
            -DnugetconfAnalyzerEnabled=false \
            -DcocoapodsAnalyzerEnabled=false \
            -DswiftPackageManagerAnalyzerEnabled=false \
            -DbundleAuditAnalyzerEnabled=false \
            -DpipAnalyzerEnabled=false \
            -DpipfileAnalyzerEnabled=false \
            -DpoetryAnalyzerEnabled=false
        continue-on-error: true

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ayush/target/dependency-check-report.html
          if-no-files-found: warn

      - name: Set up Docker image tag
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Run DAST (OWASP ZAP) against local container
      #   run: |
      #     docker run -d -p 8080:8080 --name test-app ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-bedrock:${{ env.TAG }}
      #     sleep 15
      #     docker run --rm owasp/zap2docker-stable zap-baseline.py -t http://host.docker.internal:8080 -r zap-report.html
      #     docker stop test-app && docker rm test-app

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-bedrock:${{ env.TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-bedrock:${{ env.TAG }}