name: CI/CD Pipeline bedrock

on:
  push:
    branches:
      - main

jobs:
  dockerize-spring-boot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker image tag
        id: vars
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-bedrock:${{ env.TAG }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-bedrock:${{ env.TAG }}